[package]
name = "ochenslab"
version = "0.1.0"
authors = ["Ivan Avdeev <me@w23.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
